### PR TITLE
Add ability to send additional headers

### LINKED ISSUE #6: Add customer headers to config
This is a really excellent editor. 
I want to know how to add a custom header to the attaches tool. I have an API that requires an authorization token to be sent before you can upload a file

### LINKED ISSUE #23: Additional Headers
It would be nice to add the ability to send additional headers
For example: X-CSRF-TOKEN

Just like it is available in image https://github.com/editor-js/image/blob/master/src/uploader.js
Line #L64

### PR DESCRIPTION
**Pull request by artsur**
resolves #23 
resolves #6

### CODE REVIEW

**Comment by OliverGeneser** [comment]
@talyguryn Can we get this feature merged? :-)

**Comment by Torann** [comment]
Please merge this if it's good to go. This is preventing me from using this plugin

**Comment by jere-co** [comment]
Merge please.

**Review by robonetphy — CHANGES_REQUESTED** [review]
Hi @artsur 
Please update your branch with the `master` branch, create a production build and update the version in `package.json` and we ready to merge your PR.

**Comment by artsur** [comment]
I think it is the same as https://github.com/editor-js/attaches/pull/34

Please merge one of the requests

**Comment by neSpecc** [comment]
Code is ok. Should be tested.

**Review by robonetphy — APPROVED** [review]

**Pull request merged**
