### PR TITLE
add readonly

### PR DESCRIPTION
**Pull request by Davidzhu001**

### CODE REVIEW

**Comment by Solweigdev** [comment]
UP

**Comment by aiavci** [comment]
I also wanted to add this. Can this be merged and deployed?

**Comment by ryuldashev** [comment]
🆙

**Comment by Davidzhu001** [comment]
you can folk it, i think they don't really maintain this repo well.

**Comment by neSpecc** [comment]
Thanks for the solution. The problem has been resolved via #57

**Pull request closed without merging**
